#ArcGIS Pro project location
aprx: ".\\.esri\\EditMaps.aprx"

# Database platform: ORACLE or SQLSERVER?
platform: "ORACLE"

# Post after making versioned edits?
post_edits: False

# Users that authorize versioned edits
authorizes_edits:
  "UTIL": True
  "TRANS": True
  "PW": True
  "PARKS": False

# Will edits all come from a single parent or multiple parents?
single_parent: True
single:
  SDE.DEFAULT:
    version_suffix: "_FacilityID"
    include: ["UTIL.", "TRANS.", "PW.", "PARKS."]
    exclude: []
multiple: 
  WEBEDITOR.Esri_Anonymous_util/BHSewer:
    version_suffix: "_BHSewerFacilityID"
    include: ["UTIL.SEWER"]
    exclude: []
  WEBEDITOR.Esri_Anonymous_util/BHStorm:
    version_suffix: "_BHStormFacilityID"
    include: ["UTIL.STORMWATER"]
    exclude: []
  WEBEDITOR.Esri_Anonymous_util/BHWater:
    version_suffix: "_BHWaterFacilityID"
    include: ["UTIL.WATERDISTRIBUTION"]
    exclude: []
  SDE.DEFAULT:
    version_suffix: "_FacilityID"
    include: []
    exclude: ["UTIL.SEWER", "UTIL.STORMWATER", "UTIL.WATERDISTRIBUTION"]

# Email recipients for each database user
recipients:
  UTIL: 
    - "nestlerj@bouldercolorado.gov"
    - "jefferyb@bouldercolorado.gov"
    - "salmone@bouldercolorado.gov"
  TRANS: 
    - "simpsonj@bouldercolorado.gov"
    - "gregoryk@bouldercolorado.gov"
  PW: 
    - "nestlerj@bouldercolorado.gov"
    - "jefferyb@bouldercolorado.gov"
    - "salmone@bouldercolorado.gov"
    - "simpsonj@bouldercolorado.gov"
    - "gregoryk@bouldercolorado.gov"
  PARKS: 
    - "spielmanc@bouldercolorado.gov"

# Logging Configurations
LOGGING:
  version: 1
  formatters:
    only:
      format: '%(asctime)s.%(msecs)03d : %(name)s : %(levelname)s : %(message)s'
      datefmt: '%m/%d/%Y %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: only
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: only
      filename: '.\facilityid\log\facilityid.log'
    email:
      class: logging.handlers.SMTPHandler
      mailhost: ["smtp.office365.com", 587]
      fromaddr: "noreply@bouldercolorado.gov"
      toaddrs: ["nestj1@bouldercolorado.gov"]
      subject: "An error halted the FacilityID script"
      credentials: ["noreply@bouldercolorado.gov", "3qIjkh1)vU"]
      secure: []
      level: ERROR
      formatter: only
  loggers:
    __main__:
      level: INFO
      handlers: [console, file, email]
    app:
      level: INFO
      handlers: [console, file, email]
    edit:
      level: DEBUG
      handlers: [console, file]
    identifier:
      level: DEBUG
      handlers: [console, file]
    management:
      level: DEBUG
      handlers: [console, file]

# Database configurations
DATABASES:
  ORACLE:
    connections:
      read: "S:\\GIS\\Share\\DatabaseConnections\\gis on gisprod2.sde"
      edit: "S:\\PW\\PWShare\\GIS\\Scripts\\dbconnections\\gisscr on gisprod2.sde"
    info:
      database_platform: "ORACLE"
      instance: "gisprod2"
      account_authentication: "DATABASE_AUTH"
      username: "gisscr"
      password: "gKJTZkCYS937"
      version_type: "TRANSACTIONAL"
  SQLSERVER:
    connections:
      read: "S:\\GIS\\Share\\DatabaseConnections\\SQLGISProd3\\gis on gisprod3.sde"
      edit: "S:\\GIS\\Share\\DatabaseConnections\\SQLGISProd3\\gisscr on gisprod3.sde"
    info:
      database_platform: "SQL_SERVER"
      instance: "sqlprod19gis"
      database: "gisprod3"
      account_authentication: "DATABASE_AUTH"
      username: "gisscr"
      password: ""
      version_type: "TRANSACTIONAL"
