#ArcGIS Pro project location
aprx: ".\\.esri\\EditMaps.aprx"
template_lyr: ".\\.esri\\GroupLayerTemplate.lyrx"

# Shall the script assign new ids with unused numbers between the min and
# max ID (True), or shall it increment from the max (False)?
recycle_ids: False

# Database platform: ORACLE or SQL_SERVER?
platform: "SQL_SERVER"

# Which users authorize versioned edits and post control?
authorization:
  UTIL:
    versioned_edits: True
    post_edits: False
  TRANS:
    versioned_edits: True
    post_edits: False
  PW:
    versioned_edits: True
    post_edits: False
  PARKS:
    versioned_edits: True
    post_edits: False

# Will edits all come from a single parent or multiple parents?
single_parent: True
single:
  SDE.DEFAULT:
    version_suffix: "_FacilityID"
    include: ["UTIL.", "TRANS.", "PW.", "PARKS."]
    exclude: ["Inspection"]
multiple: 
  WEBEDITOR.Esri_Anonymous_util/BHSewer:
    version_suffix: "_BHSewerFacilityID"
    include: ["UTIL.SEWER"]
    exclude: []
  WEBEDITOR.Esri_Anonymous_util/BHStorm:
    version_suffix: "_BHStormFacilityID"
    include: ["UTIL.STORMWATER"]
    exclude: []
  WEBEDITOR.Esri_Anonymous_util/BHWater:
    version_suffix: "_BHWaterFacilityID"
    include: ["UTIL.WATERDISTRIBUTION"]
    exclude: []
  SDE.DEFAULT:
    version_suffix: "_FacilityID"
    include: []
    exclude: ["UTIL.SEWER", "UTIL.STORMWATER", "UTIL.WATERDISTRIBUTION"]

# Email recipients for each database user
recipients:
  UTIL:
    - "pwgisinfores@bouldercolorado.gov"
  TRANS:
    - "pwgisinfores@bouldercolorado.gov"
  PW:
    - "pwgisinfores@bouldercolorado.gov"
  PARKS:
    - "jeffreyb@bouldercolorado.gov"

# Logging Configurations
LOGGING:
  version: 1
  formatters:
    only:
      format: '%(asctime)s.%(msecs)03d : %(name)s : %(levelname)s : %(message)s'
      datefmt: '%m/%d/%Y %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: only
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: only
      filename: '.\\facilityid\\log\\facilityid.log'
    email:
      class: logging.handlers.SMTPHandler
      mailhost: ["smtp.office365.com", 587]
      fromaddr: "noreply-gis@bouldercolorado.gov"
      toaddrs: "nestlerj@bouldercolorado.gov"
      subject: "An error halted the FacilityID script"
      secure: []
      level: ERROR
      formatter: only
  loggers:
    __main__:
      level: INFO
      handlers: [console, file, email]
    facilityid.app:
      level: INFO
      handlers: [console, file]
    facilityid.utils.edit:
      level: DEBUG
      handlers: [console, file]
    facilityid.utils.identifier:
      level: DEBUG
      handlers: [console, file]
    facilityid.utils.management:
      level: DEBUG
      handlers: [console, file]

# Database configurations
DATABASES:
  ORACLE:
    connections:
      read: "S:\\GIS\\Share\\DatabaseConnections\\gis on gisprod2.sde"
      edit: "S:\\PW\\PWShare\\GIS\\Scripts\\dbconnections\\gisscr on gisprod2.sde"
    info:
      database_platform: "ORACLE"
      instance: "gisprod2"
      account_authentication: "DATABASE_AUTH"
      username: "gisscr"
      version_type: "TRANSACTIONAL"
  SQL_SERVER:
    connections:
      read: "\\\\filesrv15\\ShareDVolNS\\Dev\\Apps16\\ORADATA\\GIS\\DatabaseConnections\\SqlServer\\Prod3\\gis on gisprod3.sde"
      edit: "\\\\filesrv15\\ShareDVolNS\\Dev\\Apps16\\ORADATA\\GIS\\DatabaseConnections\\SqlServer\\Prod3\\gisscr on gisprod3.sde"
    info:
      database_platform: "SQL_SERVER"
      instance: "GISData"
      database: "gisprod3"
      account_authentication: "DATABASE_AUTH"
      username: "gisscr"
      version_type: "TRANSACTIONAL"
