---
# Designates the scale at which to check Facility IDs
mode:
  scan_by_user: True
  scan_by_dset: False
  scan_by_feat: False

sde:
  read: "S:\\GIS\\Share\\DatabaseConnections\\gis on gisprod2.sde"
  edit: "S:\\PW\\PWShare\\GIS\\Scripts\\dbconnections\\gisscr on gisprod2.sde"

# Designates data owners, and whether they approved versioned edits
users:
  UTIL: True
  TRANS: True
  PW: True
  PARKS: True

# Update these if scan_by_dset is True
dsets:
  UTIL:
    "WATERDISTRIBUTION"
    "STORMWATER"
    "SEWER"

# Update these if scan_by_feat is True
feats:
  UTIL:
    WATERDISTRIBUTION:
      "wFitting"
      "wHydrant"
    "Floodplains"
    "Greenways"

# Defines actions required per feature to enable versioned editing
checklist:
  0 - FEATURE CLASS: []
  1 - PREFIX: []
  2 - CHECK VERSIONED EDITS: []
  3 - ENABLE GLOBALID: []
  4 - REGISTER AS VERSIONED: []
  5 - TURN ON EDITOR TRACKING: []
  6 - RE-ENABLE ACCESS TO GIS USER: []
  7 - GRANT GISSCR USER FULL PRIVILEGES: []
  8 - FILL IN FACILITY ID VALUES: []

# Categorizes number of edits made to individual features
count:
  0 - FEATURE CLASS: []
  1 - VERSIONED EDITS: []
  2 - NULL VALUES: []
  3 - DUPLICATE IDS: []
  4 - INCORRECT PREFIXES: []
  5 - LEADING ZEROS: []
  6 - DUPLICATE GEOMS: []